#define BUILD_NUMBER \
	"build-74039"
#define BUILD_NUMBER_NUMERIC \
	74039
#define BUILD_NUMBER_NUMERIC_STRING \
	"74039"
#define PRODUCT_BUILD_NUMBER \
	"product-build-80"
#define PRODUCT_BUILD_NUMBER_NUMERIC \
	80
#define PRODUCT_BUILD_NUMBER_NUMERIC_STRING \
	"80"
