#!/bin/bash

set -e

# let debhelper stop the service first...

#DEBHELPER#

# then notify vmware about it

if which systemd-detect-virt 1>/dev/null; then
    checktool='systemd-detect-virt'
else
    checktool='vmware-checkvm'
fi

if which ${checktool} 1>/dev/null && which vmware-rpctool 1>/dev/null; then
    if ${checktool} | grep -iq vmware; then
        vmware-rpctool 'tools.set.version 0' &> /dev/null || /bin/true
    fi
fi

exit 0
