#!/bin/sh

set -e


case "${1}" in
    configure)
        if [ -x /bin/systemd-tmpfiles ]
        then
            /bin/systemd-tmpfiles --create /usr/lib/tmpfiles.d/vmblock-fuse-tmpfiles.conf               
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`${1}'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
